version: '3.7'

services:
  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_PASSWORD: kPJdhFyED8K5bfy
      POSTGRES_USER: enstasy
      POSTGRES_DB:  enstasy
    restart: always
    networks:
      - enstasy
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    restart: always
    networks:
      - enstasy

  web:
    build: .
    image: enstasy/enstasy_web:v1
    command: ['sh', '-c', 'python /srv/enstasy/manage.py migrate && uwsgi --ini /srv/enstasy/uwsgi/uwsgi.ini']
    volumes:
      - .:/srv/enstacy
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - enstasy
    restart: always

env_file:
  - .env

networks:
  enstasy:

volumes:
  db_volume:
      name: db_volume
      driver: local
      driver_opts:
      type: non
      device: ${ENSTACY_WEB_SOURCE_PATH}
      o: bind

  enstacy_source:
      name: enstacy_source
      driver: local
      driver_opts:
      type: non
      device: ${ENSTACY_DB_DATA_PATH}
      o: bind

