# Generated by Django 2.1.7 on 2019-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.FilePathField(max_length=256, path='/static/', verbose_name='address')),
                ('file_type', models.CharField(choices=[('img', 'image'), ('vid', 'video'), ('audio', 'audio')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
