# Generated by Django 2.1.7 on 2019-03-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utility', '0002_auto_20190326_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.File')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.File')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_artwork', to='utility.File')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.Category')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.Chapter')),
                ('files', models.ManyToManyField(related_name='courses', to='utility.File', verbose_name='Course file')),
            ],
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utility.File')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='narrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.Narrator'),
        ),
    ]
